version: '3.8'

services:
  hadolint:
    image: hadolint/hadolint:v2.8.0
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: hadolint
    tty: true

  shellcheck:
    image: koalaman/shellcheck:v0.8.0
    volumes:
      - ./:/mnt

  argbash:
    image: matejak/argbash:2.10.0
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: ./argbash

  bats:
    build:
      context: .
      target: test
    volumes:
      - ./:/usr/src
    entrypoint: bats

  pg_dev:
    build: .
    volumes:
      - ./:/usr/src
      - ./ext/git:/usr/local/share/postgresql/extension/git
