version: '3.8'

services:
  hadolint:
    image: hadolint/hadolint:v2.12.0@sha256:30a8fd2e785ab6176eed53f74769e04f125afb2f74a6c52aef7d463583b6d45e
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: hadolint
    tty: true

  shellcheck:
    image: koalaman/shellcheck:v0.10.0@sha256:2097951f02e735b613f4a34de20c40f937a6c8f18ecb170612c88c34517221fb
    volumes:
      - ./:/mnt

  argbash:
    image: matejak/argbash:2.10.0@sha256:fb483f4ace79729280b9f63ae9c5395f829fb39c41a06ae699ecf610ea1d5713
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: ./argbash

  bats:
    build:
      context: .
      target: test
    volumes:
      - ./:/usr/src
    entrypoint: bats

  pg_dev:
    build: .
    volumes:
      - ./:/usr/src
      - ./ext/git:/usr/local/share/postgresql/extension/git
