services:
  hadolint:
    image: hadolint/hadolint:v2.13.1@sha256:1fd499f411a9ff121fda3207af1c8d32e2a92648c19fb1847553c5b79ca4c281
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: hadolint
    tty: true

  shellcheck:
    image: koalaman/shellcheck:v0.11.0@sha256:61862eba1fcf09a484ebcc6feea46f1782532571a34ed51fedf90dd25f925a8d
    volumes:
      - ./:/mnt

  argbash:
    image: matejak/argbash:2.11.0@sha256:9d4cb031d9d7ea893dd84ac02d596bb32560725d6cd1cc19d8c8933019125148
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: ./argbash

  bats:
    build:
      context: .
      target: test
    volumes:
      - ./:/usr/src
    entrypoint: bats

  pg_dev:
    build: .
    volumes:
      - ./:/usr/src
      - ./ext/git:/usr/local/share/postgresql/extension/git
