version: '3.8'

services:
  hadolint:
    image: hadolint/hadolint:v2.9.3@sha256:c90fe0d22b6aa7cb8114cd4022cf7a596f61724e2c66b4e0b03435326f29dede
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: hadolint
    tty: true

  shellcheck:
    image: koalaman/shellcheck:v0.8.0@sha256:4c4427336d2b4bdb054a1e97396fa2e9ca0c329a1f43f831b99bcaae4ac24fcd
    volumes:
      - ./:/mnt

  argbash:
    image: matejak/argbash:2.10.0@sha256:fb483f4ace79729280b9f63ae9c5395f829fb39c41a06ae699ecf610ea1d5713
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: ./argbash

  bats:
    build:
      context: .
      target: test
    volumes:
      - ./:/usr/src
    entrypoint: bats

  pg_dev:
    build: .
    volumes:
      - ./:/usr/src
      - ./ext/git:/usr/local/share/postgresql/extension/git
