#!/usr/bin/env bash
set -Eeo pipefail

if [ -z "$PG_DEV_MENU" ]; then
  exit 0
fi

key="${1:?key not set}"
desc="${2:?desc not set}"
shift 2

# delete if already exists
sed -e "/^$key\t/d" -i "$PG_DEV_MENU"

# add new command
echo -e "$key\t$desc\t$*" >> "$PG_DEV_MENU"
