#!/usr/bin/env bash
set -Eeo pipefail
set +u

function cleanup() {
  bash "$PG_DEV_TMP_DIR/cleanup" > /dev/null 2>&1
  rm -rf "$PG_DEV_TMP_DIR" > /dev/null 2>&1
}

if [ -z "$PG_DEV_TMP_DIR" ]; then
  PG_DEV_TMP_DIR="$(mktemp -d)"
  export PG_DEV_TMP_DIR
  echo '#!/usr/bin/env bash' > "$PG_DEV_TMP_DIR/cleanup"
  trap cleanup EXIT TERM
fi
