#!/usr/bin/env bash
set -Eeo pipefail

logpath="$PG_DEV_TMP_DIR/with_pg"
mkdir "$logpath" 2>/dev/null || true

# restart script as postgres user if run as root
if [ "$(id -u)" = '0' ]; then
  chmod 777 "$(dirname "$logpath")"
  chown postgres:postgres "$logpath"
  exec su-exec postgres "$0" "$@"
fi

source "$(dirname "$0")/_utils"
source "$(which docker-entrypoint.sh)"

case $1 in
  start)
    PGDATA="$(mktemp -d)"
    export PGDATA

    function cleanup() {
      "$0" stop "$PGDATA"
    }
    trap cleanup ERR

    # hook into docker_ scripts
    # shellcheck disable=SC2034
    POSTGRES_INITDB_ARGS="--no-locale --nosync --auth=trust"

    "$(dirname "$0")/_with_menu_item" i "show output for PG initdb" cat "$logpath/initdb.log"
    catch_log "$logpath/initdb.log" docker_init_database_dir

    "$(dirname "$0")/_with_menu_item" s "show output for PG startup" cat "$logpath/startup.log"
    catch_log "$logpath/startup.log" docker_temp_server_start

    "$(dirname "$0")/_with_menu_item" d "show output for PG setup_db" cat "$logpath/setup.log"
    catch_log "$logpath/setup.log" docker_setup_db

    "$(dirname "$0")/_with_menu_item" e "show output for PG docker-entrypoint-initdb.d" cat "$logpath/entrypoint.log"
    catch_log "$logpath/entrypoint.log" docker_process_init_files /docker-entrypoint-initdb.d/*

    echo "$PGDATA"
    ;;

  stop)
    PGDATA="$2"
    export PGDATA

    docker_temp_server_stop > /dev/null 2>&1
    rm -rf "$PGDATA" > /dev/null 2>&1
    ;;

  *)
    exit 1
    ;;
esac
