#!/usr/bin/env bash
set -Eeo pipefail

if [[ ! -v TMUX ]]; then
  exec "$@"
fi

tmux bind-key -n Escape "display-popup -C; run-shell $0" \
  \; set-hook -g after-new-window "display-popup -C; if-shell -F '#{m:!(async *):#W}' 'run-shell -d 1 $0'" \
  \; set -g remain-on-exit on

("$@")

(
  while true; do
    tmux refresh-client
    sleep 0.1
  done
) &
refresh_pid=$!
trap 'kill $refresh_pid' EXIT

show_key=0
(
  tmux list-windows -F '#I #W' | while read -r idx cmd; do
    case "$cmd" in
      tool|menu)
        ;;

      "watcher "*)
        echo "'Run again'" "r" "'send-keys -t $idx -H 20'"
        ;;

      "async "*)
        echo "'Show \"$cmd\"'" $((++show_key)) "'setenv PG_DEV_ACTIVE_WINDOW $idx; select-window -t $idx'"
        ;;

      *)
        echo "'Show \"$cmd\"'" $((++show_key)) "'setenv PG_DEV_ACTIVE_WINDOW $idx; select-window -t $idx; run-shell $0'"
        ;;
    esac
  done
  echo "Exit" "q" "kill-session"
) | xargs tmux menu -x 1000 -y 1000
