#!/usr/bin/env bash
set -Eeo pipefail

script_path="$(readlink -f "${BASH_SOURCE[0]}")"
# shellcheck source=tools/pg.args.bash
source "$script_path.args.bash"

source "$(which docker-entrypoint.sh)"

if [ -z "$PGPORT" ]; then
  # finds the next free port number taking into account currently active postgresql sockets
  PGPORT=5432
  until [ ! -e "/var/run/postgresql/.s.PGSQL.$PGPORT" ]; do
    ((PGPORT++))
  done
else
  # if port is given, wait until port is available
  until [ ! -e "/var/run/postgresql/.s.PGSQL.$PGPORT" ]; do
    sleep 0.1
  done
fi

docker_setup_env

PGDATA="$(mktemp -d --suffix=.pgdata)"
PGDATABASE="$POSTGRES_DB"
PGHOST=""
PGUSER="$POSTGRES_USER"
export PGDATA PGDATABASE PGHOST PGPORT PGUSER

trap '$(dirname "$0")/pg_runner stop' EXIT

"$(dirname "$0")/pg_runner" start

("${_arg_leftovers[@]}")
