#!/usr/bin/env bash
set -Eeo pipefail

script_path="$(readlink -f "${BASH_SOURCE[0]}")"
# shellcheck source=tools/pg.args.bash
source "$script_path.args.bash"

source "$(which docker-entrypoint.sh)"

# finds the max port number of currently active postgresql sockets
function find_max_port() {
  find /var/run/postgresql -maxdepth 1 -type s \
  | sed -re 's/^.*\.([0-9]+)$/\1/g' \
  | sort -nr \
  | head -n1
}
maxport="$(find_max_port)"

docker_setup_env

PGDATA="$(mktemp -d --suffix=.pgdata)"
PGDATABASE="$POSTGRES_DB"
PGHOST=""
PGPORT="$((${maxport:-5431} + 1))"
PGUSER="$POSTGRES_USER"
export PGDATA PGDATABASE PGHOST PGPORT PGUSER

trap '$(dirname "$0")/pg_runner stop' EXIT

"$(dirname "$0")/pg_runner" start

("${_arg_leftovers[@]}")
