#!/usr/bin/env bash
#
# USAGE:
# with_pg <command>
# The command is executed with PostgreSQL available. PGHOST and PGPORT are set accordingly.
# The database is shutdown and the cluster removed when the script exits.
#
set -Eeo pipefail

source "$(which docker-entrypoint.sh)"

# finds the max port number of currently active postgresql sockets
function find_max_port() {
  find /var/run/postgresql -maxdepth 1 -type s \
  | sed -re 's/^.*\.([0-9]+)$/\1/g' \
  | sort -nr \
  | head -n1
}
maxport="$(find_max_port)"

docker_setup_env

PGDATA="$(mktemp -d --suffix=.pgdata)"
PGDATABASE="$POSTGRES_DB"
PGHOST=""
PGPORT="$((${maxport:-5431} + 1))"
PGUSER="$POSTGRES_USER"
export PGDATA PGDATABASE PGHOST PGPORT PGUSER

trap '$(dirname "$0")/pg_runner stop' EXIT

"$(dirname "$0")/pg_runner" start

("$@")
