#!/usr/bin/env bash
set -Eeo pipefail

# restart script as postgres user if run as root
if [ "$(id -u)" = '0' ]; then
  chown postgres:postgres "$PGDATA"
  exec su-exec postgres "$0" "$@"
fi

source "$(which docker-entrypoint.sh)"

case $1 in
  start)
    initdb --no-locale --nosync --auth=trust --username="$PGUSER"
    pg_ctl -D "$PGDATA" -o "-p $PGPORT" -w start
    
    if [ "$PGDATABASE" != "postgres" ]; then
      createdb "$PGDATABASE"
    fi

    docker_process_init_files /docker-entrypoint-initdb.d/*
    ;;

  stop)
    pg_ctl -D "$PGDATA" -m immediate -w stop
    rm -rf "$PGDATA"
    ;;

  *)
    exit 1
    ;;
esac
