#!/usr/bin/env bash
set -Eeo pipefail

# restart script as postgres user if run as root
if [ "$(id -u)" = '0' ]; then
  chown postgres:postgres "$PGDATA"
  exec su-exec postgres "$0" "$@"
fi

source "$(which docker-entrypoint.sh)"

case $1 in
  start)
    # hook into docker_ scripts
    # shellcheck disable=SC2034
    POSTGRES_INITDB_ARGS="--no-locale --nosync --auth=trust"

    docker_init_database_dir
    docker_temp_server_start
    docker_setup_db
    docker_process_init_files /docker-entrypoint-initdb.d/*
    ;;

  stop)
    docker_temp_server_stop
    rm -rf "$PGDATA"
    ;;

  *)
    exit 1
    ;;
esac
