#!/usr/bin/env bash
set -Eeo pipefail

# restart script as postgres user if run as root
if [ "$(id -u)" = '0' ]; then
  chown postgres:postgres "$PGDATA"
  exec su-exec postgres "$0" "$@"
fi

source "$(which docker-entrypoint.sh)"

cmd="$1"
shift 1

case $cmd in
  start)
    initdb --encoding="UTF8" --no-locale --nosync --auth=trust --username="$PGUSER"
    POSTGRES_HOST_AUTH_METHOD=trust pg_setup_hba_conf
    pg_ctl -D "$PGDATA" -o "-F" -w start "$@"
    
    if [ "$PGDATABASE" != "postgres" ]; then
      createdb "$PGDATABASE"
    fi

    docker_process_init_files /docker-entrypoint-initdb.d/*
    ;;

  stop)
    pg_ctl -D "$PGDATA" -m immediate -w stop
    rm -rf "$PGDATA"
    ;;

  *)
    exit 1
    ;;
esac
