#!/usr/bin/env bash
#
# USAGE:
# pgtap
# This will:
#  - Create the pgTAP extension in a schema called pgtap.
#  - Run pg_prove on all .spec.sql files found recursively.
#
set -Eeuo pipefail

with_sql /dev/stdin <<EOF \
  pg_prove -r \
    --ext .spec.sql \
    --pgtap-option suffix=.sql \
    "$@"

CREATE SCHEMA IF NOT EXISTS pgtap;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA pgtap;
ALTER ROLE CURRENT_USER SET search_path=pgtap,public;
EOF
