#!/usr/bin/env bash
#
# USAGE:
# test <file>
# This will:
#  - Launch a temporary postgresql database via with_tmp_db.
#  - Load the file as the entrypoint to create the database schema.
#  - Create the pgTAP extension in a schema called pgtap.
#  - Run pg_prove on all .spec.sql files found recursively.
set -Eeuo pipefail

schema="${1}"
shift 1

cat - "$schema" <<EOF \
  | with_tmp_db \
    pg_prove -r \
      --ext .spec.sql \
      --pgtap-option suffix=.sql \
      "$@"

CREATE SCHEMA pgtap;
CREATE EXTENSION pgtap WITH SCHEMA pgtap;
ALTER ROLE CURRENT_USER SET search_path=pgtap,public;         
LOAD 'plpgsql_check';
ALTER ROLE CURRENT_USER SET plpgsql_check.mode = 'every_start';
ALTER ROLE CURRENT_USER SET plpgsql_check.fatal_errors = 'yes';
ALTER ROLE CURRENT_USER SET plpgsql_check.show_nonperformance_warnings = true;
ALTER ROLE CURRENT_USER SET plpgsql_check.show_performance_warnings = true;
EOF
