#!/usr/bin/env bash
set -Eeuo pipefail

if [[ -v PG_DEV_CI ]]; then
  exec "$@"
fi

if [[ ! -v TMUX ]]; then
  export PG_DEV_WINDOW=0
  tmux new -d -n tool "$@" \
    \; set -g mouse on \
    \; set -g status off
fi

if [ -t 0 ]; then
  exec tmux attach
fi

tmux_pid="$(tmux display-message -pF '#{pid}')"

cat /var/log/stdout &
trap 'kill 0' EXIT

# wait for tmux to die
while [ -e "/proc/$tmux_pid" ]; do sleep 0.1; done
