#!/usr/bin/env bash
#
# USAGE:
# with_pg <command>
# The command is executed with PostgreSQL available. PGHOST and PGPORT are set accordingly.
# The database is shutdown and the cluster removed when the script exits.
#
set -Eeo pipefail

source "$(which docker-entrypoint.sh)"

# finds the max port number of currently active postgresql sockets
function find_max_port() {
  find /var/run/postgresql -maxdepth 1 -type s \
  | sed -re 's/^.*\.([0-9]+)$/\1/g' \
  | sort -nr \
  | head -n1
}
maxport="$(find_max_port)"

docker_setup_env

PGHOST=""
PGPORT="$((${maxport:-5431} + 1))"
PGDATABASE=$POSTGRES_DB
PGUSER=$POSTGRES_USER
export PGHOST PGPORT PGDATABASE PGUSER

PGDATA=$(_with_pg_runner start)

function cleanup() {
  _with_pg_runner stop "$PGDATA"
}
trap cleanup EXIT

("$@")
