#!/usr/bin/env bash
#
# USAGE:
# with_sql <file> <command>
# Runs psql with file as input then executes command.
#
set -Eeo pipefail

file="${1:-file argument is required}"
shift 1

source "$(dirname "$0")/_with_tmp_dir"

source "$(which docker-entrypoint.sh)"

PG_DEV_WITH_SQL_COUNTER=${PG_DEV_WITH_SQL_COUNTER:-0}
PG_DEV_WITH_SQL_COUNTER=$((PG_DEV_WITH_SQL_COUNTER+1))

logfile="$PG_DEV_TMP_DIR/with_sql_$PG_DEV_WITH_SQL_COUNTER.log"

docker_process_sql -f "$file" > "$logfile" 2>&1

"$(dirname "$0")/_with_menu_item" "$PG_DEV_WITH_SQL_COUNTER" "show output for with_sql $file" cat "$logfile"

("$@")
