#!/usr/bin/env bash
#
# USAGE:
# while_watching <command>
# The command is executed and restarted with SIGTERM when any file in the current workdir changes.
#
set -Eeuo pipefail

while true; do
  # Allow re-splitting of arguments on purpose
  # shellcheck disable=SC2068
  (! ag -l . | entr -dr $@)
done
