name: Push to main

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Hadolint
        run: docker compose run --rm hadolint Dockerfile
        if: always()
      - name: Shellcheck
        run: docker compose run --rm shellcheck tools/*
        if: always()
      - name: Argbash
        run: |
          docker compose run --rm argbash
          git diff --exit-code
        if: always()

  build-test-push:
    needs: check
    strategy:
      matrix:
        pg:
          - 9.6.24
          - 10.19
          - 11.14
          - 12.9
          - 13.5
          - 14.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Login to Docker
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2.9.0
        with:
          build-args: PG_VERSION=${{ matrix.pg }}
      - name: Build Test
        uses: docker/build-push-action@v2.9.0
        with:
          build-args: PG_VERSION=${{ matrix.pg }}
          target: test
      - name: Test
        run: DOCKER_BUILDKIT=1 docker compose run --rm bats test
      - name: Push
        uses: docker/build-push-action@v2.9.0
        with:
          build-args: PG_VERSION=${{ matrix.pg }}
          push: true
          tags: technowledgy/pg_dev:${{ matrix.pg }}-alpine

  dockerhub:
    needs: build-test-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Update Docker Hub Description
        # Currently fails because of
        # https://github.com/peter-evans/dockerhub-description/issues/10 and
        # https://github.com/docker/hub-feedback/issues/1927
        continue-on-error: true
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}