name: Push to main

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - name: Hadolint
        run: docker compose run --rm hadolint Dockerfile
        if: always()
      - name: Shellcheck
        run: find tools -type f -not -iname '*.sql' | xargs docker compose run --rm shellcheck
        if: always()
      - name: Argbash
        run: |
          docker compose run --rm argbash
          git diff --exit-code
        if: always()

  build-test-push:
    needs: check
    strategy:
      matrix:
        pg: [10, 11, 12, 13, 14, 14-invoker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - name: Login to Docker
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2.10.0
        with:
          build-args: PG_MAJOR=${{ matrix.pg }}
      - name: Build Test
        uses: docker/build-push-action@v2.10.0
        with:
          build-args: PG_MAJOR=${{ matrix.pg }}
          target: test
      - name: Test
        run: DOCKER_BUILDKIT=1 docker compose run --rm bats test
      - name: Push
        uses: docker/build-push-action@v2.10.0
        with:
          build-args: PG_MAJOR=${{ matrix.pg }}
          push: true
          tags: technowledgy/pg_dev:pg${{ matrix.pg }}

  dockerhub:
    needs: build-test-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - name: Update Docker Hub Description
        # Currently fails because of
        # https://github.com/peter-evans/dockerhub-description/issues/10 and
        # https://github.com/docker/hub-feedback/issues/1927
        continue-on-error: true
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}