name: Push to main

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Hadolint
        run: docker compose run --rm hadolint Dockerfile
      - name: Shellcheck
        run: docker compose run --rm shellcheck tools/*

  build-push:
    needs: lint
    strategy:
      matrix:
        version:
          - 9.6.24
          - 10.19
          - 11.14
          - 12.9
          - 13.5
          - 14.1
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          build-args: PG_VERSION=${{ matrix.version }}
          push: true
          tags: technowledgy/pg_dev:${{ matrix.version }}-alpine
